version: '3.8'
services:
  mysql:
    image: mysql-autentia
    ports:
      - "3306:3306"
    container_name: mysql-TNT

  openldap:
    build: ldapTools/docker/openldap
    image: autentia/openldap
    ports:
      - 389:389
    environment:
      - SLAPD_DOMAIN=autentia.com
      - SLAPD_PASSWORD=adminadmin
      - SLAPD_CONFIG_PASSWORD=config
      - SLAPD_ADDITIONAL_SCHEMAS=ppolicy
      - SLAPD_ADDITIONAL_MODULES=ppolicy
    container_name: autentia-ldap
  tntconcept:
    container_name: tntconcept
    image: tntconcept
    ports:
      - '8080:8080'

